// <auto-generated />
using MT.PersonService.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MT.PersonService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MT.PersonService.Core.Entity.ContactInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UUID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UUID");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "xyz@any.com",
                            Location = "istanbul",
                            PhoneNumber = "05554443231",
                            UUID = 1
                        },
                        new
                        {
                            id = 2,
                            Email = "xyz@any.com",
                            Location = "Ankara",
                            PhoneNumber = "05554443231",
                            UUID = 1
                        });
                });

            modelBuilder.Entity("MT.PersonService.Core.Entity.Person", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UUID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            UUID = 1,
                            Company = "xyz",
                            Name = "merve",
                            SurName = "Çelik"
                        },
                        new
                        {
                            UUID = 2,
                            Company = "xyz",
                            Name = "Ipek",
                            SurName = "Ipek"
                        });
                });

            modelBuilder.Entity("MT.PersonService.Core.Entity.ContactInfo", b =>
                {
                    b.HasOne("MT.PersonService.Core.Entity.Person", "Person")
                        .WithMany("ContactInfos")
                        .HasForeignKey("UUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MT.PersonService.Core.Entity.Person", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
